# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radio_button.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 744)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_country = QtWidgets.QLabel(self.centralwidget)
        self.lbl_country.setGeometry(QtCore.QRect(60, 230, 301, 151))
        self.lbl_country.setText("")
        self.lbl_country.setObjectName("lbl_country")
        self.lbl_education = QtWidgets.QLabel(self.centralwidget)
        self.lbl_education.setGeometry(QtCore.QRect(390, 230, 351, 151))
        self.lbl_education.setText("")
        self.lbl_education.setObjectName("lbl_education")
        self.btn_country = QtWidgets.QPushButton(self.centralwidget)
        self.btn_country.setGeometry(QtCore.QRect(60, 390, 301, 181))
        self.btn_country.setObjectName("btn_country")
        self.btn_education = QtWidgets.QPushButton(self.centralwidget)
        self.btn_education.setGeometry(QtCore.QRect(390, 390, 351, 181))
        self.btn_education.setObjectName("btn_education")
        self.groupBox_country = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_country.setGeometry(QtCore.QRect(60, 30, 301, 191))
        self.groupBox_country.setObjectName("groupBox_country")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_country)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 261, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_country = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_country.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_country.setObjectName("gridLayout_country")
        self.radio_turkiye = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_turkiye.setObjectName("radio_turkiye")
        self.gridLayout_country.addWidget(self.radio_turkiye, 0, 0, 1, 1)
        self.radio_yunanistan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_yunanistan.setObjectName("radio_yunanistan")
        self.gridLayout_country.addWidget(self.radio_yunanistan, 3, 0, 1, 1)
        self.radio_almanya = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_almanya.setObjectName("radio_almanya")
        self.gridLayout_country.addWidget(self.radio_almanya, 1, 0, 1, 1)
        self.radio_azerbaycan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_azerbaycan.setObjectName("radio_azerbaycan")
        self.gridLayout_country.addWidget(self.radio_azerbaycan, 2, 0, 1, 1)
        self.groupBox_education = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_education.setGeometry(QtCore.QRect(390, 30, 351, 191))
        self.groupBox_education.setObjectName("groupBox_education")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_education)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 321, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_education = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_education.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_education.setObjectName("gridLayout_education")
        self.radio_ilkokul = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_ilkokul.setObjectName("radio_ilkokul")
        self.gridLayout_education.addWidget(self.radio_ilkokul, 0, 0, 1, 1)
        self.radio_yuksek_lisans = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_yuksek_lisans.setObjectName("radio_yuksek_lisans")
        self.gridLayout_education.addWidget(self.radio_yuksek_lisans, 3, 0, 1, 1)
        self.radio_lise = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_lise.setObjectName("radio_lise")
        self.gridLayout_education.addWidget(self.radio_lise, 1, 0, 1, 1)
        self.radio_universite = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_universite.setObjectName("radio_universite")
        self.gridLayout_education.addWidget(self.radio_universite, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_country.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.btn_education.setText(_translate("MainWindow", "Eğitim Seçimi"))
        self.groupBox_country.setTitle(_translate("MainWindow", "Ülke"))
        self.radio_turkiye.setText(_translate("MainWindow", "Türkiye"))
        self.radio_yunanistan.setText(_translate("MainWindow", "Yunanistan"))
        self.radio_almanya.setText(_translate("MainWindow", "Almanya"))
        self.radio_azerbaycan.setText(_translate("MainWindow", "Azerbaycan"))
        self.groupBox_education.setTitle(_translate("MainWindow", "Eğitim"))
        self.radio_ilkokul.setText(_translate("MainWindow", "İlkokul"))
        self.radio_yuksek_lisans.setText(_translate("MainWindow", "Yüksek Lisans"))
        self.radio_lise.setText(_translate("MainWindow", "Lise"))
        self.radio_universite.setText(_translate("MainWindow", "Üniversite"))
